# Generated by Django 4.1.2 on 2022-11-22 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0005_alter_discount_code_alter_discount_value_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.CharField(default='NAW6288I', max_length=10),
        ),
        migrations.AlterField(
            model_name='discount',
            name='value_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed amount', 'Fixed Amount'), ('free shipping', 'Free Shipping')], default='percentage', max_length=50),
        ),
    ]
